name: "Report a problem"
description: "Если что-то работает не так, как ожидалось."
labels: ["triage"]
body:
  - type: textarea
    id: description
    validations:
      required: true
    attributes:
      label: "Description"
      description: "Describe the problem as detailed as possible"

  - type: textarea
    id: reproduction
    attributes:
      label: "Reproduction steps"
      description: "If you can provide steps to reproduce this issue, please do so"
      placeholder: |
        1. Open console
        2. Press start
        3. Get error message...

  - type: textarea
    id: screenshots
    attributes:
      label: "Screenshots"
      description: |
        If applicable, add screenshots to help explain your problem. You can drag and drop images below.
